#!/usr/bin/env bash
# Install Nginx Web Server on an Ubuntu machine

apt-get update && apt-get install -y nginx > /dev/null 2>&1
service nginx stop

cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80;
	root /usr/share/nginx/html;
	index index.html;
}
EOF

echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx start
