#!/usr/bin/env bash
# Install Nginx Web Server on an Ubuntu machine and
# redirect all traffic of /redirect_me to other website

apt-get update && apt-get install -y nginx
service nginx stop

cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80;
	root /usr/share/nginx/html;
	index index.html;
	location / {
		rewrite ^(/redirect_me.*) https://moz.com/learn/seo/redirection permanent;
	}
}
EOF

echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx start
