#!/usr/bin/env bash
# Install Nginx Web Server on an Ubuntu machine and
# redirect all traffic of /redirect_me to other website
# also configure a custom 404 page

apt-get update && apt-get install -y nginx
service nginx stop

cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80;
	root /usr/share/nginx/html;
	index index.html;
	location / {
		error_page 404 /404.html;
		rewrite ^(/redirect_me.*) https://moz.com/learn/seo/redirection permanent;
	}
}
EOF

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx start
