#!/usr/bin/env bash
# Make the Nginx run as nginx user(just 8 lines)
pkill apache2
sed -i.bak '/^\tlisten.*80/s/80/8080/' /etc/nginx/sites-available/default
sed -i.bak '/^#user/ c\user nginx;' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
