#!/usr/bin/env bash
# Install and configures haproxy as load balancer

haconf='/etc/haproxy/haproxy.cfg'

apt-get install -y software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.5 -y
apt-get update
apt-get install -y haproxy

sed -i.bak '/\tmode\thttp/ a\\toption\tforwardfor' $haconf

cat << EOF >> $haconf

frontend http-frontend
	bind *:80
	default_backend wwwbackend

backend wwwbackend
	balance roundrobin
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	server 23-web-01 158.69.78.253:80 check
	server 23-web-02 204.236.242.13:80 check

listen stats *:9000
        stats enable
        stats uri /haproxy_stats
        stats hide-version
        stats auth admin:12345
EOF

service haproxy restart
