name             'holberton-wrapper'
maintainer       'Alexandro de Oliveira'
maintainer_email 'alexandro.oliveira@holbertonschool.com'
license          'All rights reserved'
description      'Installs/Configures holberton-wrapper'
long_description 'Installs/Configures holberton-wrapper'
version          '0.1.0'

depends 'apt',      '~> 4.0.1'
depends 'ntp',      '~> 2.0.0'
depends 'openssh',  '~> 2.0.0'
depends 'user',     '~> 0.4.2'
