#!/usr/bin/env bash
# Management of process/daemons with start, stop restart

MY_PROCESS='manage_my_process'

usage()
{
	printf '%s\n' "Usage: $(basename "$0") {start|stop|restart}"
	exit 1
}

if [ $# -ne 1 ]
then
	usage
fi

cat <<\EOF > "$MY_PROCESS" && chmod +x $MY_PROCESS
#!/usr/bin/env bash
# This script is the "worker" to be managed

PID=$$
PIDFILE='/var/run/my_process.pid'
echo "$PID" > $PIDFILE

remove()
{
	rm -f $PIDFILE
	exit 0
}

trap remove SIGTERM

init()
{
	while :
	do
		echo 'I am alive!' >> /tmp/my_process
		sleep 2
	done
}

init
exit 0
EOF


start()
{
	./$MY_PROCESS > /dev/null 2>&1 &
	echo "$MY_PROCESS $1"
}

stop()
{
	pkill -fx "bash ./$MY_PROCESS"
	echo "$MY_PROCESS stopped"
}

restart()
{
	pkill -fx "bash ./$MY_PROCESS"
	sleep 2
	start "restarted"
}

case "$1" in
	start)
		start "start"
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		usage
		;;
esac
