#!/usr/bin/env bash
# Management of process/daemons with start, stop restart

DAEMON='manage_my_process'
PIDFILE='/var/run/my_process.pid'

usage()
{
	printf '%s\n' "Usage: ${DAEMON} {start|stop|restart}"
	exit 1
}

if [[ $# -ne 1 ]]
then
	usage
fi

# Create the file to be managed(if the file doesn't exist), make it executable
[[ -e "$DAEMON" ]] || (cat <<\EOF > "$DAEMON" && chmod +x $DAEMON)
#!/bin/sh
# This script is the "worker" to be managed

PID=$$
PIDFILE='/var/run/my_process.pid'
echo "$PID" | sudo tee "$PIDFILE" > /dev/null

cleanup()
{
	sudo rm -f $PIDFILE
	exit 0
}

trap cleanup 15

init()
{
	while :
	do
		echo 'I am alive!' >> /tmp/my_process
		sleep 2
	done
}

init
EOF

wait_pidfile()
{
	# If $1 is not set(parameter not given) it waits for pid file creation
	# When parameter is given it waits for pid file removal
	[[ -z ${1+x} ]] && TEST="[ -e $PIDFILE ]" || TEST="[ ! -e $PIDFILE ]"
	until $TEST; do :; done
}

start()
{
	sh $DAEMON > /dev/null 2>&1 &
	wait_pidfile
	echo "$DAEMON $1"
}

stop()
{
	pkill -fx "sh $DAEMON"
	wait_pidfile 1
	echo "$DAEMON stopped"
}

restart()
{
	pkill -fx "sh $DAEMON"
	wait_pidfile 1
	start "restarted"
}

case "$1" in
	start)
		start "started"
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		usage
		;;
esac
