#!/usr/bin/env bash
# Catches software interrupt signals, loop some msg, prints its PID to a file
PID=$$
PIDFILE=/var/run/holbertonscript.pid

function cleanquit
{
	rm "$PIDFILE"
	exit
}

echo $PID > $PIDFILE
trap "echo 'I hate the kill command'; cleanquit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "cleanquit" SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done

