#!/bin/sh
# This script is the "worker" to be managed

PID=$$
PIDFILE='/var/run/my_process.pid'
echo "$PID" | sudo tee "$PIDFILE" > /dev/null

cleanup()
{
	sudo rm -f $PIDFILE
	exit 0
}

trap cleanup 15

init()
{
	while :
	do
		echo 'I am alive!' >> /tmp/my_process
		sleep 2
	done
}

init
